# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pantallaInicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_principal = QtWidgets.QFrame(self.centralwidget)
        self.frame_principal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.frame_argenchess = QtWidgets.QFrame(self.frame_principal)
        self.frame_argenchess.setGeometry(QtCore.QRect(190, 80, 271, 311))
        self.frame_argenchess.setStyleSheet("background-color: rgb(185, 213, 239);\n"
"border-radius: 10px;")
        self.frame_argenchess.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_argenchess.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_argenchess.setObjectName("frame_argenchess")
        self.frame_menu = QtWidgets.QFrame(self.frame_argenchess)
        self.frame_menu.setGeometry(QtCore.QRect(60, 60, 161, 191))
        self.frame_menu.setStyleSheet("background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.btn_jugar = QtWidgets.QPushButton(self.frame_menu)
        self.btn_jugar.setGeometry(QtCore.QRect(30, 30, 101, 23))
        self.btn_jugar.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_jugar.setObjectName("btn_jugar")
        self.btn_aprender = QtWidgets.QPushButton(self.frame_menu)
        self.btn_aprender.setGeometry(QtCore.QRect(30, 70, 101, 23))
        self.btn_aprender.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_aprender.setObjectName("btn_aprender")
        self.btn_herramientas = QtWidgets.QPushButton(self.frame_menu)
        self.btn_herramientas.setGeometry(QtCore.QRect(30, 110, 101, 23))
        self.btn_herramientas.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_herramientas.setObjectName("btn_herramientas")
        self.pushButton_preferencias = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_preferencias.setGeometry(QtCore.QRect(30, 150, 101, 23))
        self.pushButton_preferencias.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_preferencias.setObjectName("pushButton_preferencias")
        self.label_argenchess = QtWidgets.QLabel(self.frame_argenchess)
        self.label_argenchess.setGeometry(QtCore.QRect(60, 20, 171, 41))
        self.label_argenchess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_argenchess.setStyleSheet("font: 25pt \"Bauhaus 93\";")
        self.label_argenchess.setObjectName("label_argenchess")
        self.frame_jugar = QtWidgets.QFrame(self.frame_argenchess)
        self.frame_jugar.setGeometry(QtCore.QRect(0, 0, 271, 301))
        self.frame_jugar.setStyleSheet("background-color: rgb(185, 213, 239);\n"
"border-radius: 10px;")
        self.frame_jugar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_jugar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_jugar.setObjectName("frame_jugar")
        self.frame_menu_jugar = QtWidgets.QFrame(self.frame_jugar)
        self.frame_menu_jugar.setGeometry(QtCore.QRect(60, 60, 161, 171))
        self.frame_menu_jugar.setStyleSheet("background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.frame_menu_jugar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_jugar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_jugar.setObjectName("frame_menu_jugar")
        self.btn_vsAmigo = QtWidgets.QPushButton(self.frame_menu_jugar)
        self.btn_vsAmigo.setGeometry(QtCore.QRect(30, 50, 101, 23))
        self.btn_vsAmigo.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_vsAmigo.setObjectName("btn_vsAmigo")
        self.btn_vsOrdenador = QtWidgets.QPushButton(self.frame_menu_jugar)
        self.btn_vsOrdenador.setGeometry(QtCore.QRect(30, 110, 101, 23))
        self.btn_vsOrdenador.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_vsOrdenador.setObjectName("btn_vsOrdenador")
        self.label_jugar = QtWidgets.QLabel(self.frame_jugar)
        self.label_jugar.setGeometry(QtCore.QRect(100, 20, 81, 41))
        self.label_jugar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_jugar.setStyleSheet("font: 25pt \"Bauhaus 93\";")
        self.label_jugar.setObjectName("label_jugar")
        self.btn_play_back = QtWidgets.QPushButton(self.frame_jugar)
        self.btn_play_back.setGeometry(QtCore.QRect(20, 270, 101, 31))
        self.btn_play_back.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.btn_play_back.setObjectName("btn_play_back")
        self.frame_aprender = QtWidgets.QFrame(self.frame_argenchess)
        self.frame_aprender.setGeometry(QtCore.QRect(0, 0, 271, 311))
        self.frame_aprender.setStyleSheet("background-color: rgb(185, 213, 239);\n"
"border-radius: 10px;")
        self.frame_aprender.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_aprender.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_aprender.setObjectName("frame_aprender")
        self.frame_menu_aprender = QtWidgets.QFrame(self.frame_aprender)
        self.frame_menu_aprender.setGeometry(QtCore.QRect(60, 60, 161, 201))
        self.frame_menu_aprender.setStyleSheet("background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.frame_menu_aprender.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_aprender.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_aprender.setObjectName("frame_menu_aprender")
        self.btn_basico = QtWidgets.QPushButton(self.frame_menu_aprender)
        self.btn_basico.setGeometry(QtCore.QRect(30, 20, 101, 23))
        self.btn_basico.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_basico.setObjectName("btn_basico")
        self.btn_finales = QtWidgets.QPushButton(self.frame_menu_aprender)
        self.btn_finales.setGeometry(QtCore.QRect(30, 110, 101, 23))
        self.btn_finales.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_finales.setObjectName("btn_finales")
        self.btn_apertura = QtWidgets.QPushButton(self.frame_menu_aprender)
        self.btn_apertura.setGeometry(QtCore.QRect(30, 50, 101, 23))
        self.btn_apertura.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_apertura.setObjectName("btn_apertura")
        self.btn_medioJuego = QtWidgets.QPushButton(self.frame_menu_aprender)
        self.btn_medioJuego.setGeometry(QtCore.QRect(30, 80, 101, 23))
        self.btn_medioJuego.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_medioJuego.setObjectName("btn_medioJuego")
        self.btn_ejercicios = QtWidgets.QPushButton(self.frame_menu_aprender)
        self.btn_ejercicios.setGeometry(QtCore.QRect(30, 140, 101, 23))
        self.btn_ejercicios.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_ejercicios.setObjectName("btn_ejercicios")
        self.btn_openBook = QtWidgets.QPushButton(self.frame_menu_aprender)
        self.btn_openBook.setGeometry(QtCore.QRect(30, 170, 101, 23))
        self.btn_openBook.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_openBook.setObjectName("btn_openBook")
        self.label_aprender = QtWidgets.QLabel(self.frame_aprender)
        self.label_aprender.setGeometry(QtCore.QRect(70, 20, 141, 41))
        self.label_aprender.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_aprender.setStyleSheet("font: 25pt \"Bauhaus 93\";")
        self.label_aprender.setObjectName("label_aprender")
        self.btn_aprende_back = QtWidgets.QPushButton(self.frame_aprender)
        self.btn_aprende_back.setGeometry(QtCore.QRect(10, 270, 101, 31))
        self.btn_aprende_back.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.btn_aprende_back.setObjectName("btn_aprende_back")
        self.frame_herramientas = QtWidgets.QFrame(self.frame_argenchess)
        self.frame_herramientas.setGeometry(QtCore.QRect(10, 10, 271, 311))
        self.frame_herramientas.setStyleSheet("background-color: rgb(185, 213, 239);\n"
"border-radius: 10px;")
        self.frame_herramientas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_herramientas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_herramientas.setObjectName("frame_herramientas")
        self.frame_menu_herramientas = QtWidgets.QFrame(self.frame_herramientas)
        self.frame_menu_herramientas.setGeometry(QtCore.QRect(50, 70, 161, 171))
        self.frame_menu_herramientas.setStyleSheet("background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.frame_menu_herramientas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_herramientas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_herramientas.setObjectName("frame_menu_herramientas")
        self.btn_editBoard = QtWidgets.QPushButton(self.frame_menu_herramientas)
        self.btn_editBoard.setGeometry(QtCore.QRect(30, 30, 111, 23))
        self.btn_editBoard.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_editBoard.setObjectName("btn_editBoard")
        self.btn_analisis = QtWidgets.QPushButton(self.frame_menu_herramientas)
        self.btn_analisis.setGeometry(QtCore.QRect(30, 80, 101, 23))
        self.btn_analisis.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_analisis.setObjectName("btn_analisis")
        self.btn_dataBase = QtWidgets.QPushButton(self.frame_menu_herramientas)
        self.btn_dataBase.setGeometry(QtCore.QRect(30, 130, 101, 23))
        self.btn_dataBase.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_dataBase.setObjectName("btn_dataBase")
        self.label_herramientas = QtWidgets.QLabel(self.frame_herramientas)
        self.label_herramientas.setGeometry(QtCore.QRect(40, 30, 201, 41))
        self.label_herramientas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_herramientas.setStyleSheet("font: 25pt \"Bauhaus 93\";")
        self.label_herramientas.setObjectName("label_herramientas")
        self.btn_herramientas_back = QtWidgets.QPushButton(self.frame_herramientas)
        self.btn_herramientas_back.setGeometry(QtCore.QRect(0, 260, 101, 31))
        self.btn_herramientas_back.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.btn_herramientas_back.setObjectName("btn_herramientas_back")
        self.frame_preferencias = QtWidgets.QFrame(self.frame_argenchess)
        self.frame_preferencias.setGeometry(QtCore.QRect(10, 10, 271, 311))
        self.frame_preferencias.setStyleSheet("background-color: rgb(185, 213, 239);\n"
"border-radius: 10px;")
        self.frame_preferencias.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_preferencias.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preferencias.setObjectName("frame_preferencias")
        self.frame_menu_preferencias = QtWidgets.QFrame(self.frame_preferencias)
        self.frame_menu_preferencias.setGeometry(QtCore.QRect(50, 70, 161, 161))
        self.frame_menu_preferencias.setStyleSheet("background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.frame_menu_preferencias.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_preferencias.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_preferencias.setObjectName("frame_menu_preferencias")
        self.btn_visual = QtWidgets.QPushButton(self.frame_menu_preferencias)
        self.btn_visual.setGeometry(QtCore.QRect(30, 30, 101, 23))
        self.btn_visual.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_visual.setObjectName("btn_visual")
        self.btn_idioma = QtWidgets.QPushButton(self.frame_menu_preferencias)
        self.btn_idioma.setGeometry(QtCore.QRect(30, 70, 101, 23))
        self.btn_idioma.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_idioma.setObjectName("btn_idioma")
        self.btn_sonido = QtWidgets.QPushButton(self.frame_menu_preferencias)
        self.btn_sonido.setGeometry(QtCore.QRect(30, 110, 101, 23))
        self.btn_sonido.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_sonido.setObjectName("btn_sonido")
        self.label_preferencias = QtWidgets.QLabel(self.frame_preferencias)
        self.label_preferencias.setGeometry(QtCore.QRect(40, 20, 181, 41))
        self.label_preferencias.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_preferencias.setStyleSheet("font: 25pt \"Bauhaus 93\";")
        self.label_preferencias.setObjectName("label_preferencias")
        self.btn_preferencias_back = QtWidgets.QPushButton(self.frame_preferencias)
        self.btn_preferencias_back.setGeometry(QtCore.QRect(0, 260, 101, 31))
        self.btn_preferencias_back.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.btn_preferencias_back.setObjectName("btn_preferencias_back")
        self.frame_visual = QtWidgets.QFrame(self.frame_preferencias)
        self.frame_visual.setGeometry(QtCore.QRect(-10, 10, 271, 311))
        self.frame_visual.setStyleSheet("background-color: rgb(185, 213, 239);\n"
"border-radius: 10px;")
        self.frame_visual.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_visual.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_visual.setObjectName("frame_visual")
        self.frame_menu_visual = QtWidgets.QFrame(self.frame_visual)
        self.frame_menu_visual.setGeometry(QtCore.QRect(10, 40, 251, 201))
        self.frame_menu_visual.setStyleSheet("background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.frame_menu_visual.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_visual.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_visual.setObjectName("frame_menu_visual")
        self.btn_boardb = QtWidgets.QPushButton(self.frame_menu_visual)
        self.btn_boardb.setGeometry(QtCore.QRect(150, 20, 51, 51))
        self.btn_boardb.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/board/tablero_blanco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_boardb.setIcon(icon)
        self.btn_boardb.setIconSize(QtCore.QSize(50, 50))
        self.btn_boardb.setObjectName("btn_boardb")
        self.btn_boardm = QtWidgets.QPushButton(self.frame_menu_visual)
        self.btn_boardm.setGeometry(QtCore.QRect(40, 20, 51, 51))
        self.btn_boardm.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../image/board/tablero_marron.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_boardm.setIcon(icon1)
        self.btn_boardm.setIconSize(QtCore.QSize(50, 50))
        self.btn_boardm.setObjectName("btn_boardm")
        self.btn_disenio1 = QtWidgets.QPushButton(self.frame_menu_visual)
        self.btn_disenio1.setGeometry(QtCore.QRect(150, 150, 51, 41))
        self.btn_disenio1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../image/piece/modelo1/kb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_disenio1.setIcon(icon2)
        self.btn_disenio1.setIconSize(QtCore.QSize(35, 50))
        self.btn_disenio1.setObjectName("btn_disenio1")
        self.btn_disenio2 = QtWidgets.QPushButton(self.frame_menu_visual)
        self.btn_disenio2.setGeometry(QtCore.QRect(30, 150, 51, 41))
        self.btn_disenio2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../image/piece/modelo2/kb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_disenio2.setIcon(icon3)
        self.btn_disenio2.setIconSize(QtCore.QSize(35, 35))
        self.btn_disenio2.setObjectName("btn_disenio2")
        self.btn_colorm = QtWidgets.QPushButton(self.frame_menu_visual)
        self.btn_colorm.setGeometry(QtCore.QRect(40, 100, 41, 23))
        self.btn_colorm.setStyleSheet("background-color: rgb(170, 98, 56);")
        self.btn_colorm.setText("")
        self.btn_colorm.setObjectName("btn_colorm")
        self.btn_colorb = QtWidgets.QPushButton(self.frame_menu_visual)
        self.btn_colorb.setGeometry(QtCore.QRect(160, 100, 41, 23))
        self.btn_colorb.setStyleSheet("background-color: rgb(170, 98, 56);\n"
"background-color: rgb(11, 11, 11);")
        self.btn_colorb.setText("")
        self.btn_colorb.setObjectName("btn_colorb")
        self.lbl_colorBoard = QtWidgets.QLabel(self.frame_menu_visual)
        self.lbl_colorBoard.setGeometry(QtCore.QRect(10, 0, 101, 20))
        self.lbl_colorBoard.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lbl_colorBoard.setObjectName("lbl_colorBoard")
        self.lbl_colorPiece = QtWidgets.QLabel(self.frame_menu_visual)
        self.lbl_colorPiece.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.lbl_colorPiece.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lbl_colorPiece.setObjectName("lbl_colorPiece")
        self.lbl_disenioPiece = QtWidgets.QLabel(self.frame_menu_visual)
        self.lbl_disenioPiece.setGeometry(QtCore.QRect(10, 130, 101, 20))
        self.lbl_disenioPiece.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lbl_disenioPiece.setObjectName("lbl_disenioPiece")
        self.label_visual = QtWidgets.QLabel(self.frame_visual)
        self.label_visual.setGeometry(QtCore.QRect(90, 0, 91, 31))
        self.label_visual.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_visual.setStyleSheet("font: 25pt \"Bauhaus 93\";")
        self.label_visual.setObjectName("label_visual")
        self.btn_visual_back = QtWidgets.QPushButton(self.frame_visual)
        self.btn_visual_back.setGeometry(QtCore.QRect(10, 250, 101, 31))
        self.btn_visual_back.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.btn_visual_back.setObjectName("btn_visual_back")
        self.frame_idioma = QtWidgets.QFrame(self.frame_preferencias)
        self.frame_idioma.setGeometry(QtCore.QRect(0, 0, 271, 311))
        self.frame_idioma.setStyleSheet("background-color: rgb(185, 213, 239);\n"
"border-radius: 10px;")
        self.frame_idioma.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_idioma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_idioma.setObjectName("frame_idioma")
        self.frame_menu_idioma = QtWidgets.QFrame(self.frame_idioma)
        self.frame_menu_idioma.setGeometry(QtCore.QRect(50, 50, 161, 171))
        self.frame_menu_idioma.setStyleSheet("background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.frame_menu_idioma.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_idioma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_idioma.setObjectName("frame_menu_idioma")
        self.btn_spanish = QtWidgets.QPushButton(self.frame_menu_idioma)
        self.btn_spanish.setGeometry(QtCore.QRect(40, 40, 75, 23))
        self.btn_spanish.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.btn_spanish.setObjectName("btn_spanish")
        self.btn_english = QtWidgets.QPushButton(self.frame_menu_idioma)
        self.btn_english.setGeometry(QtCore.QRect(40, 110, 75, 23))
        self.btn_english.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.btn_english.setObjectName("btn_english")
        self.label_idioma = QtWidgets.QLabel(self.frame_idioma)
        self.label_idioma.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.label_idioma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_idioma.setStyleSheet("font: 25pt \"Bauhaus 93\";")
        self.label_idioma.setObjectName("label_idioma")
        self.btn_idioma_back = QtWidgets.QPushButton(self.frame_idioma)
        self.btn_idioma_back.setGeometry(QtCore.QRect(10, 250, 101, 31))
        self.btn_idioma_back.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.btn_idioma_back.setObjectName("btn_idioma_back")
        self.frame_sonido = QtWidgets.QFrame(self.frame_preferencias)
        self.frame_sonido.setGeometry(QtCore.QRect(10, 10, 271, 311))
        self.frame_sonido.setStyleSheet("background-color: rgb(185, 213, 239);\n"
"border-radius: 10px;")
        self.frame_sonido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sonido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sonido.setObjectName("frame_sonido")
        self.frame_menu_idioma_2 = QtWidgets.QFrame(self.frame_sonido)
        self.frame_menu_idioma_2.setGeometry(QtCore.QRect(50, 50, 161, 171))
        self.frame_menu_idioma_2.setStyleSheet("background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.frame_menu_idioma_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_idioma_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_idioma_2.setObjectName("frame_menu_idioma_2")
        self.ckb_activar = QtWidgets.QCheckBox(self.frame_menu_idioma_2)
        self.ckb_activar.setGeometry(QtCore.QRect(30, 70, 121, 17))
        self.ckb_activar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.ckb_activar.setObjectName("ckb_activar")
        self.label_sonido = QtWidgets.QLabel(self.frame_sonido)
        self.label_sonido.setGeometry(QtCore.QRect(70, 10, 111, 31))
        self.label_sonido.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_sonido.setStyleSheet("font: 25pt \"Bauhaus 93\";")
        self.label_sonido.setObjectName("label_sonido")
        self.btn_sonido_back = QtWidgets.QPushButton(self.frame_sonido)
        self.btn_sonido_back.setGeometry(QtCore.QRect(10, 250, 101, 31))
        self.btn_sonido_back.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(42, 65, 100);\n"
"border-radius: 10px;")
        self.btn_sonido_back.setObjectName("btn_sonido_back")
        self.verticalLayout.addWidget(self.frame_principal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_jugar.setText(_translate("MainWindow", "Jugar"))
        self.btn_aprender.setText(_translate("MainWindow", "Aprender"))
        self.btn_herramientas.setText(_translate("MainWindow", "Herramientas"))
        self.pushButton_preferencias.setText(_translate("MainWindow", "Preferencias"))
        self.label_argenchess.setText(_translate("MainWindow", "Argenchess"))
        self.btn_vsAmigo.setText(_translate("MainWindow", "Vs amigo"))
        self.btn_vsOrdenador.setText(_translate("MainWindow", "Vs Ordenador"))
        self.label_jugar.setText(_translate("MainWindow", "Jugar"))
        self.btn_play_back.setText(_translate("MainWindow", "Volver"))
        self.btn_basico.setText(_translate("MainWindow", "Nivel Basico"))
        self.btn_finales.setText(_translate("MainWindow", "Finales"))
        self.btn_apertura.setText(_translate("MainWindow", "Apertura"))
        self.btn_medioJuego.setText(_translate("MainWindow", "Medio Juego"))
        self.btn_ejercicios.setText(_translate("MainWindow", "Ejercicios"))
        self.btn_openBook.setText(_translate("MainWindow", "Abrir Libro"))
        self.label_aprender.setText(_translate("MainWindow", "Aprender"))
        self.btn_aprende_back.setText(_translate("MainWindow", "Volver"))
        self.btn_editBoard.setText(_translate("MainWindow", "Editar Tablero"))
        self.btn_analisis.setText(_translate("MainWindow", "Analisis"))
        self.btn_dataBase.setText(_translate("MainWindow", "Base de datos"))
        self.label_herramientas.setText(_translate("MainWindow", "Herramientas"))
        self.btn_herramientas_back.setText(_translate("MainWindow", "Volver"))
        self.btn_visual.setText(_translate("MainWindow", "Visual"))
        self.btn_idioma.setText(_translate("MainWindow", "Idioma"))
        self.btn_sonido.setText(_translate("MainWindow", "Sonido"))
        self.label_preferencias.setText(_translate("MainWindow", "Preferencias"))
        self.btn_preferencias_back.setText(_translate("MainWindow", "Volver"))
        self.lbl_colorBoard.setText(_translate("MainWindow", "Color Tablero"))
        self.lbl_colorPiece.setText(_translate("MainWindow", "Color Piezas"))
        self.lbl_disenioPiece.setText(_translate("MainWindow", "Diseño Piezas"))
        self.label_visual.setText(_translate("MainWindow", "Visual"))
        self.btn_visual_back.setText(_translate("MainWindow", "Volver"))
        self.btn_spanish.setText(_translate("MainWindow", "Español"))
        self.btn_english.setText(_translate("MainWindow", "English"))
        self.label_idioma.setText(_translate("MainWindow", "Idioma"))
        self.btn_idioma_back.setText(_translate("MainWindow", "Volver"))
        self.ckb_activar.setText(_translate("MainWindow", "Activar"))
        self.label_sonido.setText(_translate("MainWindow", "Sonido"))
        self.btn_sonido_back.setText(_translate("MainWindow", "Volver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
